services:
  checkin-api-pg:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=checkinapi
    ports:
      - "5432:5432"